#!/usr/bin/python3

import sys
from optparse import OptionParser
from LambdaCalc import *

def testReductions():
    print("Running reduction unit tests...")

    # Simple formulas
    assert str(Var("x").red()) == "x"
    assert str(Abs("x", Var("M")).red()) == "(Lx.M)"
    assert str(App(Var("M"), Var("N")).red()) == "(M N)"

    # Applications of variables
    assert str(App(Var("x"), Var("y")).red()) == "(x y)"
    assert str(App(Var("x"), Abs("x", Var("M"))).red()) == "(x (Lx.M))"
    assert str(App(Var("x"), App(Var("M"), Var("N"))).red()) == "(x (M N))"

    # Applications of basic abstractions
    assert str(App(Abs("x", Var("x")), Var("x")).red()) == "x"
    assert str(App(Abs("x", Var("x")), Abs("x", Var("x"))).red()) == "(Lx.x)"
    assert str(App(Abs("x", Var("x")), App(Var("M"), Var("N"))).red()) == "(M N)"

    # Application of abstraction with capture-avoiding substitution
    assert str(App(Abs("x", Var("M")), Var("x")).red()) == "M"
    assert str(App(Abs("x", Var("M")), Var("z")).red()) == "M"
    assert str(App(Abs("x", Var("x")), Var("r")).red()) == "r"
    assert str(App(Abs("x", Var("y")), Var("r")).red()) == "y"
    assert str(App(Abs("x", App(Var("t"), Var("s"))), Var("r")).red()) == "(t s)"
    assert str(App(Abs("x", App(Var("x"), Var("x"))), Var("r")).red()) == "(r r)"
    assert str(App(Abs("x", Abs("x", Var("t"))), Var("r")).red()) == "(Lx.t)"
    body = Abs("x", App(Var("x"), Var("y")))
    abst = Abs("y", body)
    assert str(App(abst, Var("x")).red()) == "(L@0.(@0 x))" # renaming example (alpha-conversion)
    resetFresh()

    # Application of applications
    assert str(App(App(Var("M"), Var("N")), Var("x")).red()) == "((M N) x)"
    assert str(App(App(Var("M"), Var("N")), Abs("x", Var("x"))).red()) == "((M N) (Lx.x))"
    assert str(App(App(Var("M"), Var("N")), App(Var("A"), Var("B"))).red()) =="((M N) (A B))"

    print("Unit tests for reductions passed!")

def testChurchEncoding():
    print("Running Church encoding unit tests...")

    # Test encoding
    zero = "(Lf.(Lx.x))"
    one = "(Lf.(Lx.(f x)))"
    two = "(Lf.(Lx.(f (f x))))"
    three = "(Lf.(Lx.(f (f (f x)))))"
    assert str(encode(0)) == zero
    assert str(encode(1)) == one
    assert str(encode(2)) == two
    assert str(encode(3)) == three

    # Test decoding
    assert decode(parse(zero)) == 0
    assert decode(parse(one)) == 1
    assert decode(parse(two)) == 2
    assert decode(parse(three)) == 3

    # Test inverse property for encode/decode
    assert decode(encode(0)) == 0
    assert decode(encode(1)) == 1
    assert decode(encode(2)) == 2
    assert decode(encode(3)) == 3
    assert str(encode(decode(parse(zero)))) == zero
    assert str(encode(decode(parse(one)))) == one
    assert str(encode(decode(parse(two)))) == two
    assert str(encode(decode(parse(three)))) == three

    # Test successor function
    assert str(succ(parse(zero))) == one
    assert str(succ(parse(one))) == two
    assert str(succ(parse(two))) == three
    print("Unit tests for Church encodings passed!")

def testInfiniteLoop():
    print("Running infinite loop tests...")
    infloop = parse("((Lx.(x x)) (Lx.(x x)))")
    for i in range(10):
        assert str(infloop) == str(infloop.red())
        infloop = infloop.red()
    try:
        infloop.bigRed()
        assert False
    except RecursionError:
        pass
    print("Infinite loop tests passed!")

parser = OptionParser()
parser.add_option("-f", "--file", dest="filename", help="path to lambda calc file", type=str)
(options, args) = parser.parse_args()
if options.filename:
    print("Running basic test file...")
    with open(options.filename) as f:
        rawInput = f.read()
        print("Raw input: %s" % rawInput[0:-1])
        parsedExpr = parse(rawInput)
        print("Parsed expression: %s" % parsedExpr)
        redExpr = parsedExpr.red()
        print("Reduced expression: %s" % redExpr)
else:
    testReductions()
    testChurchEncoding()
    testInfiniteLoop()

